const practiceAreas = [
  {
    slug: "cyber-law",
    title: "Cyber Law",
    icon: "Shield",
    teaser: "Protecting you in the digital space.",
    description: "We provide strategic legal assistance in cybercrime, online fraud, data privacy, digital transactions, and technology-related disputes, helping individuals and businesses protect their rights through effective legal solutions.",
    introduction: "Cyber Law deals with legal issues arising from the use of technology, the internet, digital platforms, and electronic communications. As digital transactions and online interactions continue to grow, individuals and businesses increasingly require legal support to address cyber-related risks and ensure compliance with applicable laws.",
    services: "At BPS Legal, we provide legal assistance in matters involving cybercrime, online fraud, identity theft, hacking, phishing, cyber harassment, data privacy and protection, digital payment disputes, social media offences, electronic evidence, technology-related disputes, legal notices, regulatory compliance, and representation before the appropriate authorities and courts.",
    tags: ["Cybercrime", "Online Fraud", "Data Privacy", "Digital Transactions"],
    clientSituations: "Our services are designed for individuals, startups, businesses, professionals, and organizations facing cyber-related legal challenges. Whether you have been affected by an online financial fraud, unauthorized access to confidential information, digital defamation, or require preventive legal advice for your business, we offer practical legal solutions tailored to your needs.",
    ourApproach: "We adopt a strategic and result-oriented approach by carefully assessing each matter, providing clear legal advice, preparing accurate documentation, assisting with complaints and compliance requirements, exploring amicable resolutions where appropriate, and offering strong representation before the relevant authorities and courts. Every matter is handled with complete confidentiality and personalized attention.",
    professionalSupport: "At BPS Legal, we are committed to protecting your digital rights through practical legal guidance, strategic representation, and reliable legal support. If you require assistance with any cyber law matter, our team is ready to help you navigate the legal process with confidence.",
  },
  {
    slug: "criminal-law",
    title: "Criminal Law",
    icon: "Scale",
    teaser: "Vigorous defense, every step of the way.",
    description: "We provide strategic legal assistance in criminal matters, including offences, investigations, complaints, and court proceedings, with focused representation, practical advice, and protection of clients’ legal rights.",
    introduction: "Criminal Law deals with offences against individuals, property, society, and the State, along with the legal procedures governing investigation, prosecution, defence, and trial. Criminal proceedings can have serious consequences for an individual’s liberty, reputation, and personal or professional life, making timely and effective legal representation essential.",
    services: "At BPS Legal, we assist clients in a wide range of criminal matters, including criminal complaints, FIR-related matters, investigation proceedings, criminal trials, appeals, revisions, summons and warrants, offences involving fraud, cheating, assault, theft, forgery, intimidation, and other criminal allegations. We also provide legal advice, representation before the police and relevant authorities, and effective representation before the appropriate courts.",
    tags: ["Criminal Trials", "Appeals & Revisions", "White Collar Crime", "Cheque Bounce"],
    clientSituations: "Our criminal law services are intended for individuals who are accused of an offence, facing criminal proceedings, or seeking to initiate legal action against an offender. We also assist clients who require immediate legal intervention during investigation, police proceedings, or court proceedings, particularly where their liberty, reputation, property, or legal rights may be at risk.",
    ourApproach: "We adopt a strategic and result-focused approach to every criminal matter. Our process begins with a detailed understanding of the facts, followed by careful legal assessment, examination of available evidence, preparation of necessary documents and legal submissions, and development of an appropriate case strategy. Where appropriate, we explore negotiation and other legally permissible remedies while ensuring strong representation before the relevant courts and authorities. Every matter is handled with personalized attention and strict confidentiality.",
    professionalSupport: "At BPS Legal, we understand the seriousness and sensitivity of criminal proceedings. We are committed to providing clear legal advice, strategic representation, and practical support throughout the legal process. If you are facing a criminal matter or require legal assistance in initiating proceedings, BPS Legal is prepared to protect your rights and represent your interests with diligence and professionalism.",
  },
  {
    slug: "bail-matters",
    title: "Bail Matters",
    icon: "Key",
    teaser: "Timely relief when it matters most.",
    description: "We assist clients in regular, anticipatory, and interim bail matters with strategic legal advice, timely representation, and focused efforts to protect liberty and secure appropriate relief.",
    introduction: "Bail is an important legal remedy that allows an accused person to seek release from custody while criminal proceedings continue. Since matters involving personal liberty often require immediate legal intervention, timely and effective representation can play a critical role in securing appropriate relief.",
    services: "At BPS Legal, we assist clients in regular bail, anticipatory bail, interim bail, bail extensions, cancellation of bail, and other bail-related proceedings. We provide legal consultation, prepare and review necessary applications and supporting documents, develop appropriate legal grounds, and represent clients before the competent courts.",
    tags: ["Regular Bail", "Anticipatory Bail", "Interim Bail", "Bail Cancellation"],
    clientSituations: "Our bail services are intended for individuals who apprehend arrest, have already been arrested, are facing criminal proceedings, or require continued protection or relief during the course of a case. We assist clients and their families in navigating urgent situations where personal liberty is at stake.",
    ourApproach: "We adopt a strategic and timely approach to bail matters, beginning with a careful assessment of the allegations, FIR or complaint, available evidence, procedural history, and individual circumstances of the client. Based on this assessment, we develop appropriate legal grounds, prepare the necessary pleadings, and provide focused representation before the relevant court. Each matter is handled with personalized attention, confidentiality, and a clear focus on securing the appropriate legal relief.",
    professionalSupport: "At BPS Legal, we understand the urgency and sensitivity associated with matters involving personal liberty. We provide practical legal guidance and dedicated representation throughout the bail process, keeping the client's interests at the forefront. If you or a family member requires assistance in a bail matter, BPS Legal is committed to providing timely, strategic, and professional legal support.",
  },
  {
    slug: "family-law",
    title: "Family Law",
    icon: "Heart",
    teaser: "Compassionate counsel for personal matters.",
    description: "We assist clients with divorce, maintenance, child custody, domestic disputes, and other family matters through practical legal advice, sensitive representation, and solutions tailored to their individual circumstances.",
    introduction: "Family Law deals with legal matters arising from marriage, separation, divorce, family relationships, and disputes concerning the rights and responsibilities of family members. As such matters often involve significant emotional and personal concerns, they require not only sound legal advice but also a sensitive and practical approach.",
    services: "At BPS Legal, we assist clients in matters relating to divorce, mutual consent divorce, judicial separation, maintenance, child custody and visitation, domestic violence, matrimonial disputes, restitution of conjugal rights, and other family-related proceedings. We also provide assistance with legal notices, petitions, documentation, negotiation, mediation, and representation before the appropriate courts and authorities.",
    tags: ["Divorce", "Child Custody", "Maintenance & Alimony", "Marriage Registration"],
    clientSituations: "Our family law services are intended for individuals dealing with marital disputes, separation, divorce proceedings, financial or maintenance concerns, child custody issues, domestic disputes, or other conflicts involving family rights and responsibilities. We assist clients who require legal guidance to understand their rights, evaluate their options, and take appropriate legal action.",
    ourApproach: "We adopt a balanced and client-focused approach to family disputes, beginning with a detailed understanding of the client's circumstances, concerns, and objectives. Depending on the nature of the matter, we explore negotiation, mediation, and mutually acceptable solutions where appropriate, while remaining prepared to provide strong court representation when litigation becomes necessary. Every matter is handled with personalized attention, discretion, confidentiality, and sensitivity.",
    professionalSupport: "At BPS Legal, we recognize that family disputes can be deeply personal and challenging. Our objective is to provide clear legal guidance and practical solutions while protecting our clients' rights and interests throughout the process. If you require assistance with a family or matrimonial matter, BPS Legal is committed to providing confidential, compassionate, and effective legal representation.",
  },
  {
    slug: "immigration-law",
    title: "Immigration Law",
    icon: "Globe",
    teaser: "Guidance across borders.",
    description: "We assist individuals and families with immigration-related legal matters, documentation, visa issues, and regulatory requirements through practical guidance and personalized legal support.",
    introduction: "Immigration Law governs the legal processes relating to travel, migration, visas, residence, employment, and other matters involving movement across international borders. Immigration procedures can involve complex documentation and regulatory requirements, making accurate legal guidance important for avoiding delays, complications, or adverse outcomes.",
    services: "At BPS Legal, we provide legal assistance in immigration-related matters, including visa and immigration documentation, immigration compliance, residency-related issues, legal notices, representation before relevant authorities, and assistance with immigration disputes and proceedings. We also help clients understand applicable legal requirements and prepare appropriate documentation based on the nature of their matter.",
    tags: ["NRI Consultation", "Documentation Support", "Cross-Border Matters", "Legal Compliance"],
    clientSituations: "ur immigration services are intended for individuals, families, professionals, students, entrepreneurs, and businesses dealing with immigration-related legal concerns. Whether a client requires assistance with documentation, faces an immigration dispute, or needs legal guidance regarding applicable rules and procedures, we provide solutions tailored to their circumstances.",
    ourApproach: "We follow a structured and client-focused approach by first understanding the client's immigration objectives and circumstances, reviewing the relevant documents and legal requirements, identifying potential issues, and providing clear legal guidance. Where necessary, we assist with documentation, legal representations, correspondence, and proceedings before the appropriate authorities. Each matter is handled with personalized attention, confidentiality, and careful attention to applicable legal requirements.",
    professionalSupport: "At BPS Legal, we aim to simplify complex immigration-related legal processes through practical advice, careful documentation, and strategic legal assistance. If you require support with an immigration matter, our team is committed to providing professional, confidential, and personalized legal guidance suited to your specific needs.",
  },
  {
    slug: "consumer-law",
    title: "Consumer Law",
    icon: "Tag",
    teaser: "Standing up for consumer rights.",
    description: "We assist consumers in matters involving defective products, deficient services, unfair practices, and consumer disputes through practical legal advice, effective representation, and strategic resolution.",
    introduction: "Consumer Law protects individuals against unfair trade practices, defective goods, deficient services, misleading representations, and other violations of consumer rights. It provides legal remedies to consumers who suffer financial loss, inconvenience, or other harm due to the actions or omissions of businesses and service providers.",
    services: "At BPS Legal, we assist clients with consumer complaints, disputes relating to defective products and deficient services, unfair trade practices, misleading advertisements, refund and compensation claims, e-commerce disputes, and other consumer-related matters. Our services include legal consultation, drafting and filing of consumer complaints, preparation of supporting documents, negotiation where appropriate, and representation before the relevant consumer commissions and authorities.",
    tags: ["Consumer Complaints", "Defective Products", "E-commerce Disputes", "Compensation Claims"],
    clientSituations: "Our consumer law services are intended for individuals who have purchased goods or engaged services and subsequently faced defects, deficiencies, unfair treatment, financial loss, or other consumer-related grievances. We also assist clients who require legal guidance in determining their rights, available remedies, and the appropriate course of action against a seller, manufacturer, service provider, or other business entity.",
    ourApproach: "We take a structured and result-focused approach by carefully reviewing the transaction, relevant documents, communications, invoices, agreements, and other available evidence. Based on the circumstances, we advise clients on the appropriate legal remedy, assist with legal notices and complaint drafting, explore settlement or negotiation where suitable, and provide representation before the competent consumer forums. Every matter is handled with personalized attention, transparency, and confidentiality.",
    professionalSupport: "At BPS Legal, we are committed to helping clients understand and effectively exercise their consumer rights. Through practical legal advice, careful documentation, and focused representation, we seek to provide efficient and appropriate solutions to consumer disputes. If you are facing a consumer-related grievance, BPS Legal is committed to providing professional and personalized legal support.",
  },
  {
    slug: "corporate-law",
    title: "Corporate Law",
    icon: "Briefcase",
    teaser: "Legal clarity for growing businesses.",
    description: "We assist businesses with corporate legal matters, contracts, compliance, transactions, and disputes through practical legal advice, strategic planning, and personalized legal support.",
    introduction: "Corporate Law governs the legal framework within which companies and businesses are established, operated, managed, and regulated. From day-to-day legal requirements to complex business transactions and disputes, sound legal guidance helps businesses protect their interests and make legally informed decisions.",
    services: "At BPS Legal, we assist businesses and organizations with a range of corporate legal matters, including contract drafting and review, commercial agreements, corporate documentation, legal notices, regulatory and statutory compliance, business transactions, corporate disputes, and other legal issues arising during business operations. We also provide legal guidance to help clients identify and address potential legal risks.",
    tags: ["Contracts & Agreements", "Compliance", "Business Disputes", "Corporate Documentation"],
    clientSituations: "Our corporate law services are suitable for startups, entrepreneurs, companies, business owners, professionals, and established organizations requiring legal assistance in their commercial activities. Clients may seek our support when entering into agreements, managing contractual relationships, addressing compliance requirements, resolving business disputes, or making important commercial decisions involving legal considerations.",
    ourApproach: "We adopt a strategic and commercially conscious approach by first understanding the client's business objectives, operational requirements, and potential legal risks. We carefully review relevant documents, agreements, and regulatory requirements, provide clear legal advice, assist with drafting and negotiation, and represent clients in corporate or commercial disputes where necessary. Our focus is on providing practical legal solutions that support business objectives while protecting our clients' legal and commercial interests.",
    professionalSupport: "At BPS Legal, we understand that effective corporate legal support must align with the practical realities of business. We are committed to providing clear, responsive, and commercially focused legal assistance that enables clients to make informed decisions and manage legal risks with confidence. If your business requires corporate legal support, BPS Legal is ready to provide personalized and strategic legal guidance.",
  },
  {
    slug: "arbitration-adr",
    title: "Arbitration & ADR",
    icon: "Handshake",
    teaser: "Resolution without the courtroom.",
    description: "We assist clients in arbitration, mediation, negotiation, and other dispute resolution matters through strategic legal advice, effective representation, and practical solutions focused on efficient resolution.",
    introduction: "Arbitration and Alternative Dispute Resolution (ADR) provide structured mechanisms for resolving disputes without relying exclusively on conventional court proceedings. These methods can offer parties a more flexible, efficient, and commercially practical way to resolve contractual, business, and other legal disputes.",
    services: "At BPS Legal, we assist clients in arbitration and ADR matters, including arbitration proceedings, appointment of arbitrators, drafting and review of arbitration agreements, preparation of claims and responses, interim relief, enforcement of arbitral awards, mediation, negotiation, and other dispute resolution processes. We also provide legal advice and representation at different stages of arbitration proceedings.",
    tags: ["Arbitration Proceedings", "Mediation", "Conciliation", "Dispute Clauses"],
    clientSituations: "Our arbitration and ADR services are suitable for businesses, companies, individuals, professionals, and other parties involved in contractual or commercial disputes. Clients may seek our assistance when an agreement contains an arbitration clause, when a dispute has already arisen, or when they wish to explore negotiation or mediation as an alternative to prolonged litigation.",
    ourApproach: "We adopt a strategic and solution-oriented approach by carefully examining the underlying agreement, dispute, contractual obligations, evidence, and applicable legal framework. We assist clients in developing appropriate strategies, preparing pleadings and supporting documents, conducting negotiations or mediation where suitable, and providing focused representation throughout arbitration proceedings. Our objective is to protect the client's interests while pursuing an efficient and commercially sensible resolution.",
    professionalSupport: "At BPS Legal, we believe that effective dispute resolution requires a combination of strong legal strategy, careful preparation, and practical judgment. Whether through arbitration, mediation, negotiation, or other appropriate ADR mechanisms, we are committed to providing personalized, confidential, and professional legal support focused on protecting your interests and achieving an effective resolution.",
  },
  {
    slug: "legal-drafting-documentation",
    title: "Legal Drafting & Documentation",
    icon: "FileSignature",
    teaser: "Precision in every document.",
    description: "We provide professional legal drafting and documentation services, including agreements, notices, contracts, petitions, and other legal documents, with precision, clarity, and attention to each client's requirements.",
    introduction: "Legal drafting and documentation form the foundation of many legal, personal, and commercial transactions. Properly drafted documents help clearly establish rights, obligations, responsibilities, and legal remedies while reducing the scope for ambiguity, disputes, and future legal complications.",
    services: "At BPS Legal, we assist clients with drafting, reviewing, and revising a wide range of legal documents, including contracts, agreements, legal notices, affidavits, petitions, applications, undertakings, declarations, representations, deeds, memoranda, and other legal documents. We also review existing documents to identify potential legal risks, unclear provisions, inconsistencies, or clauses that may adversely affect the client's interests.",
    tags: ["Legal Notices", "Agreements & Contracts", "Affidavits", "Lease Agreements"],
    clientSituations: "Our legal drafting services are suitable for individuals, families, professionals, entrepreneurs, startups, businesses, and organizations requiring legally sound and carefully structured documentation. Clients may require our assistance when entering into agreements, responding to legal disputes, formalizing commercial or personal arrangements, making legal representations, or preparing documents for court or other legal proceedings.",
    ourApproach: "We take a precise and client-focused approach to legal drafting. We first understand the client's objectives, circumstances, and intended outcome before preparing or reviewing the relevant document. Each document is carefully structured with appropriate legal language, clear terms, and provisions designed to protect the client's interests. Where required, we also assist with negotiation, revisions, execution, and related legal procedures.",
    professionalSupport: "At BPS Legal, we understand that a well-drafted legal document can play a crucial role in protecting rights and preventing future disputes. We are committed to providing accurate, practical, and professionally prepared documentation tailored to each client's specific requirements. If you require assistance with legal drafting or documentation, BPS Legal is ready to provide confidential and personalized legal support.",
  },
  {
    slug: "ipr",
    title: "Intellectual Property Rights (IPR)",
    icon: "Lightbulb",
    teaser: "Protecting original ideas and work.",
    description: "We assist clients with trademark, copyright, brand protection, and intellectual property disputes through strategic legal advice, documentation, enforcement, and effective representation to safeguard valuable intellectual assets.",
    introduction: "Intellectual Property Rights (IPR) protect creations, brands, creative works, and other forms of intellectual assets from unauthorized use or infringement. For businesses, entrepreneurs, creators, and professionals, protecting intellectual property is essential for preserving ownership, commercial value, and brand identity.",
    services: "At BPS Legal, we assist clients with matters relating to trademarks, copyrights, brand protection, intellectual property infringement, legal notices, objections, disputes, and enforcement of intellectual property rights. We also provide assistance with drafting and reviewing IP-related agreements, licensing arrangements, and other legal documentation, along with representation before the appropriate authorities and courts.",
    tags: ["Trademark Matters", "Copyright Protection", "IP Disputes", "Brand Protection"],
    clientSituations: "Our IPR services are suitable for businesses, startups, entrepreneurs, creators, artists, authors, professionals, and organizations seeking to protect or enforce their intellectual property. Clients may require legal assistance when their brand, creative work, trademark, copyrighted material, or other intellectual asset is being misused, copied, infringed, or commercially exploited without authorization.",
    ourApproach: "We adopt a strategic and commercially focused approach by first understanding the nature and ownership of the intellectual property involved. We assess the available documentation and evidence, identify potential infringement or legal risks, and advise clients on appropriate protective or enforcement measures. Where required, we assist with legal notices, negotiations, documentation, and proceedings before the relevant authorities and courts. Every matter is handled with personalized attention and strict confidentiality.",
    professionalSupport: "At BPS Legal, we understand that intellectual property can represent significant creative, commercial, and reputational value. Our objective is to help clients protect these valuable rights through practical legal advice, strategic action, and effective representation. If you require assistance with an IPR matter, BPS Legal is committed to providing professional, confidential, and personalized legal support.",
  },
  {
    slug: "cheque-bounce-ni",
    title: "Cheque Bounce & Negotiable Instruments",
    icon: "FileWarning",
    teaser: "Swift action under the NI Act.",
    description: "We assist clients in cheque dishonour matters, statutory notices, Section 138 proceedings, and related disputes through strategic legal advice, timely action, and effective court representation.",
    introduction: "Cheque bounce matters generally arise when a cheque issued towards a legally enforceable liability is dishonoured by the bank. Such matters are governed by the applicable provisions of the Negotiable Instruments Act and may involve specific statutory requirements and timelines, making timely legal action important.",
    services: "At BPS Legal, we assist clients in matters relating to cheque dishonour, including Section 138 proceedings, issuance of statutory legal notices, preparation and filing of complaints, responses to cheque bounce notices, defence in cheque dishonour cases, and related proceedings. We also assist clients with documentation, legal advice, settlement negotiations, and representation before the competent courts.",
    tags: ["Section 138 NI Act", "Notice Drafting", "Complaint Filing", "Trial Representation"],
    clientSituations: "Our services are intended for individuals, businesses, companies, traders, professionals, and other parties who have issued or received a dishonoured cheque. We assist payees seeking recovery and legal remedies as well as individuals or businesses facing allegations or proceedings arising from cheque dishonour.",
    ourApproach: "We follow a strategic and time-sensitive approach by carefully examining the cheque, underlying transaction, bank return memo, communications, supporting documents, and applicable statutory requirements. Based on the circumstances, we advise clients on the appropriate legal course, assist with statutory notices and documentation, explore settlement where commercially appropriate, and provide focused representation before the relevant courts. Every matter is handled with personalized attention and confidentiality.",
    professionalSupport: "At BPS Legal, we understand the importance of timely and legally compliant action in cheque dishonour matters. We provide practical legal guidance and focused representation aimed at protecting our client's financial and legal interests. If you are dealing with a cheque bounce matter, BPS Legal is committed to providing professional, strategic, and personalized legal support.",
  },
];

export default practiceAreas;