const practiceAreas = [
  {
    slug: "cyber-law",
    title: "Cyber Law",
    icon: "Shield",
    teaser: "Protecting you in the digital space.",
    description: "We provide strategic legal assistance in cybercrime, online fraud, data privacy, digital transactions, and technology-related disputes, helping individuals and businesses protect their rights through effective legal solutions.",
    introduction: "Cyber Law deals with legal issues arising from the use of technology, the internet, digital platforms, and electronic communications. As digital transactions and online interactions continue to grow, individuals and businesses increasingly require legal support to address cyber-related risks and ensure compliance with applicable laws.",
    services: "At BPS Legal, we provide legal assistance in matters involving cybercrime, online fraud, identity theft, hacking, phishing, cyber harassment, data privacy and protection, digital payment disputes, social media offences, electronic evidence, technology-related disputes, legal notices, regulatory compliance, and representation before the appropriate authorities and courts.",
    tags: ["Cybercrime", "Online Fraud", "Data Privacy", "Digital Transactions"],
    clientSituations: "Our services are designed for individuals, startups, businesses, professionals, and organizations facing cyber-related legal challenges. Whether you have been affected by an online financial fraud, unauthorized access to confidential information, digital defamation, or require preventive legal advice for your business, we offer practical legal solutions tailored to your needs.",
    ourApproach: "We adopt a strategic and result-oriented approach by carefully assessing each matter, providing clear legal advice, preparing accurate documentation, assisting with complaints and compliance requirements, exploring amicable resolutions where appropriate, and offering strong representation before the relevant authorities and courts. Every matter is handled with complete confidentiality and personalized attention.",
    professionalSupport: "At BPS Legal, we are committed to protecting your digital rights through practical legal guidance, strategic representation, and reliable legal support. If you require assistance with any cyber law matter, our team is ready to help you navigate the legal process with confidence.",
  },
  {
    slug: "criminal-law",
    title: "Criminal Law",
    icon: "Scale",
    teaser: "Vigorous defense, every step of the way.",
    description: "We provide strategic legal assistance in criminal matters, including offences, investigations, complaints, and court proceedings, with focused representation, practical advice, and protection of clients’ legal rights.",
    introduction: "Criminal Law deals with offences against individuals, property, society, and the State, along with the legal procedures governing investigation, prosecution, defence, and trial. Criminal proceedings can have serious consequences for an individual’s liberty, reputation, and personal or professional life, making timely and effective legal representation essential.",
    services: "At BPS Legal, we assist clients in a wide range of criminal matters, including criminal complaints, FIR-related matters, investigation proceedings, criminal trials, appeals, revisions, summons and warrants, offences involving fraud, cheating, assault, theft, forgery, intimidation, and other criminal allegations. We also provide legal advice, representation before the police and relevant authorities, and effective representation before the appropriate courts.",
    tags: ["Criminal Trials", "Appeals & Revisions", "White Collar Crime", "Cheque Bounce"],
    clientSituations: "Our criminal law services are intended for individuals who are accused of an offence, facing criminal proceedings, or seeking to initiate legal action against an offender. We also assist clients who require immediate legal intervention during investigation, police proceedings, or court proceedings, particularly where their liberty, reputation, property, or legal rights may be at risk.",
    ourApproach: "We adopt a strategic and result-focused approach to every criminal matter. Our process begins with a detailed understanding of the facts, followed by careful legal assessment, examination of available evidence, preparation of necessary documents and legal submissions, and development of an appropriate case strategy. Where appropriate, we explore negotiation and other legally permissible remedies while ensuring strong representation before the relevant courts and authorities. Every matter is handled with personalized attention and strict confidentiality.",
    professionalSupport: "At BPS Legal, we understand the seriousness and sensitivity of criminal proceedings. We are committed to providing clear legal advice, strategic representation, and practical support throughout the legal process. If you are facing a criminal matter or require legal assistance in initiating proceedings, BPS Legal is prepared to protect your rights and represent your interests with diligence and professionalism.",
  },
  {
    slug: "bail-matters",
    title: "Bail Matters",
    icon: "Key",
    teaser: "Timely relief when it matters most.",
    description: "Timely and strategic assistance in securing bail, whether pre-arrest or post-arrest, tailored to the urgency of each case.",
    introduction: "Bail matters are time-sensitive by nature. Whether you're seeking protection before an anticipated arrest or relief after one, prompt and well-prepared legal action makes all the difference.",
    services: "We handle regular bail, anticipatory bail under Section 438 CrPC, interim bail applications, and bail cancellation matters before Sessions and High Courts.",
    tags: ["Regular Bail", "Anticipatory Bail", "Interim Bail", "Bail Cancellation"],
    clientSituations: "Common situations include fear of arrest in a non-bailable offence, post-arrest detention, or the need to respond urgently to a bail-cancellation application filed against you.",
    ourApproach: "Given the urgency involved, we prioritize rapid case assessment and same-day filing wherever possible, without compromising on the strength of the application.",
    professionalSupport: "We coordinate closely with families during what is often a high-stress period, keeping communication clear and frequent.",
  },
  {
    slug: "family-law",
    title: "Family Law",
    icon: "Heart",
    teaser: "Compassionate counsel for personal matters.",
    description: "Sensitive, practical legal support for divorce, custody, and matrimonial disputes, handled with discretion and care.",
    introduction: "Family law matters are deeply personal. We approach every case with the sensitivity it deserves, while providing the clear, practical legal guidance needed to move forward.",
    services: "Our family law practice covers mutual and contested divorce, child custody arrangements, domestic violence cases, maintenance and alimony, and marriage registration.",
    tags: ["Divorce", "Child Custody", "Maintenance & Alimony", "Marriage Registration"],
    clientSituations: "Clients typically reach out when navigating separation, custody disputes, or when they need protection and recourse in cases involving domestic violence.",
    ourApproach: "We prioritize amicable resolution where possible, while preparing thoroughly for contested proceedings when negotiation isn't an option.",
    professionalSupport: "Confidentiality and empathy guide every interaction — we understand these cases affect more than just the legal outcome.",
  },
  {
    slug: "immigration-law",
    title: "Immigration Law",
    icon: "Globe",
    teaser: "Guidance across borders.",
    description: "Legal support for visa matters, documentation, and cross-border legal concerns for individuals and NRIs.",
    introduction: "Whether you're an NRI managing legal matters back home or navigating cross-border documentation, our immigration law practice provides clear, practical guidance.",
    services: "We assist with visa-related legal documentation, NRI legal consultations, and cross-jurisdictional matters that require coordination between Indian law and international requirements.",
    tags: ["NRI Consultation", "Documentation Support", "Cross-Border Matters", "Legal Compliance"],
    clientSituations: "Clients often reach out while residing abroad and needing legal representation or documentation handled in India on their behalf.",
    ourApproach: "We accommodate different time zones and prioritize digital communication, ensuring NRI clients face no disadvantage in accessing timely legal support.",
    professionalSupport: "All documentation is handled with strict accuracy, given the compliance stakes involved in cross-border legal matters.",
  },
  {
    slug: "consumer-law",
    title: "Consumer Law",
    icon: "Tag",
    teaser: "Standing up for consumer rights.",
    description: "Representation in consumer disputes, from defective products to service failures and e-commerce complaints.",
    introduction: "Consumers often face an uphill battle against larger companies. Our consumer law practice levels the field, helping clients pursue fair resolution and compensation.",
    services: "We handle consumer complaint filings, disputes over defective products and services, e-commerce transaction disputes, and compensation claims before consumer forums.",
    tags: ["Consumer Complaints", "Defective Products", "E-commerce Disputes", "Compensation Claims"],
    clientSituations: "Clients typically approach us after receiving a defective product, poor service, or being denied a refund or replacement they're legally entitled to.",
    ourApproach: "We assess the strength of the claim early and pursue the most efficient forum — often resolving matters faster than clients expect.",
    professionalSupport: "We keep the process straightforward and jargon-free, since most consumer clients are navigating the legal system for the first time.",
  },
  {
    slug: "corporate-law",
    title: "Corporate Law",
    icon: "Briefcase",
    teaser: "Legal clarity for growing businesses.",
    description: "Practical legal support for startups and businesses, from contracts to compliance and dispute resolution.",
    introduction: "Businesses need legal partners who understand both the law and the pace of business. Our corporate law practice supports startups and established businesses alike.",
    services: "We assist with contract drafting and review, regulatory compliance, corporate documentation, and dispute resolution involving business partners or vendors.",
    tags: ["Contracts & Agreements", "Compliance", "Business Disputes", "Corporate Documentation"],
    clientSituations: "Clients typically engage us for contract review before a deal, or when a business relationship has broken down and needs legal resolution.",
    ourApproach: "We aim to prevent disputes before they arise through careful documentation, while being fully prepared to litigate when necessary.",
    professionalSupport: "We work at the pace businesses need, understanding that delayed legal support often means delayed business decisions.",
  },
  {
    slug: "arbitration-adr",
    title: "Arbitration & ADR",
    icon: "Handshake",
    teaser: "Resolution without the courtroom.",
    description: "Efficient dispute resolution through arbitration and alternative dispute resolution mechanisms.",
    introduction: "Not every dispute needs to go through lengthy litigation. Our arbitration and ADR practice helps clients resolve conflicts efficiently, outside the traditional courtroom process.",
    services: "We represent clients in arbitration proceedings, mediation, and conciliation, drafting arbitration clauses and agreements that minimize future disputes.",
    tags: ["Arbitration Proceedings", "Mediation", "Conciliation", "Dispute Clauses"],
    clientSituations: "Clients often come to us when a contract dispute has arisen and an arbitration clause is already in place, or when they prefer a faster resolution route.",
    ourApproach: "We focus on efficient, well-documented proceedings that respect the time and cost advantages ADR is meant to offer.",
    professionalSupport: "We guide clients through unfamiliar ADR procedures clearly, so they understand each step of the process.",
  },
  {
    slug: "legal-drafting-documentation",
    title: "Legal Drafting & Documentation",
    icon: "FileSignature",
    teaser: "Precision in every document.",
    description: "Accurate, enforceable legal documentation — from notices to agreements — drafted with care.",
    introduction: "Well-drafted legal documents prevent disputes before they happen. Our documentation practice ensures every agreement, notice, and affidavit is precise and enforceable.",
    services: "We draft and review legal notices, contracts and agreements, affidavits, MOUs, and lease or rent agreements, ensuring clarity and legal soundness throughout.",
    tags: ["Legal Notices", "Agreements & Contracts", "Affidavits", "Lease Agreements"],
    clientSituations: "Clients reach out before entering an agreement, when responding to a legal notice, or when they need a document formally verified.",
    ourApproach: "We draft with foresight — anticipating potential disputes and closing gaps that could otherwise be exploited later.",
    professionalSupport: "Every document undergoes careful review before finalization, prioritizing clarity over unnecessary legal jargon.",
  },
  {
    slug: "ipr",
    title: "Intellectual Property Rights (IPR)",
    icon: "Lightbulb",
    teaser: "Protecting original ideas and work.",
    description: "Legal protection for trademarks, copyrights, and original creative or business work.",
    introduction: "Original ideas and creative work deserve legal protection. Our IPR practice helps individuals and businesses safeguard what they've built.",
    services: "We assist with trademark and copyright matters, IP-related disputes, and legal protection strategies for creative and business assets.",
    tags: ["Trademark Matters", "Copyright Protection", "IP Disputes", "Brand Protection"],
    clientSituations: "Clients typically approach us when facing unauthorized use of their work or brand, or when seeking to protect new creative or business assets.",
    ourApproach: "We combine protective strategy with enforcement readiness, ensuring clients are prepared to act if infringement occurs.",
    professionalSupport: "We help clients understand IP protection as an ongoing process, not a one-time filing.",
  },
  {
    slug: "cheque-bounce-ni",
    title: "Cheque Bounce & Negotiable Instruments",
    icon: "FileWarning",
    teaser: "Swift action under the NI Act.",
    description: "Legal action and defense in cheque bounce cases under the Negotiable Instruments Act.",
    introduction: "Cheque bounce cases move quickly under the Negotiable Instruments Act, and timely legal action is essential — whether you're pursuing a claim or defending one.",
    services: "We represent both complainants and defendants in Section 138 NI Act proceedings, including notice drafting, complaint filing, and full trial representation.",
    tags: ["Section 138 NI Act", "Notice Drafting", "Complaint Filing", "Trial Representation"],
    clientSituations: "Clients reach out either after a cheque has bounced and they need to initiate legal proceedings, or after being served notice themselves.",
    ourApproach: "Given strict statutory timelines under the NI Act, we act quickly to ensure no procedural deadline is missed.",
    professionalSupport: "We guide clients clearly through each stage of what is often their first experience with criminal-adjacent proceedings.",
  },
];

export default practiceAreas;